services:
  blinkbridge:
    image: rogerdammit/blinkbridge
    container_name: blinkbridge
    restart: always
    network_mode: "host"
    volumes:
      - ./blinkbridge-config:/config
      - type: tmpfs
        target: /working
        tmpfs:
          size: 52428800  # 50MB
    tty: true
    environment:
      - BLINKBRIDGE_CONFIG=/config/config.json
    depends_on:
      - mediamtx

  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    restart: always
    network_mode: "host"

  cam-recorder:
    build: .
    container_name: cam_recorder
    restart: always
    network_mode: "host"
    depends_on:
      - blinkbridge
      - mediamtx
    env_file:
      - .env
    tmpfs:
      - /tmp/cam-segments:size=256m
    volumes:
      - /mnt/data/camera-stream:/recordings
    stop_grace_period: 60s
