services:
  blink-bridge:
    build: https://github.com/roger-/blinkbridge.git
    container_name: blink_bridge
    restart: always
    network_mode: "host"
    environment:
      - BLINK_USERNAME=${BLINK_USERNAME}
      - BLINK_PASSWORD=${BLINK_PASSWORD}
    entrypoint:
      - /bin/sh
      - -c
      - |
        cat <<EOF > config.json
        {
          "still_video_duration": 0.5,
          "cameras": {
            "enabled": [],
            "disabled": [],
            "max_failures": 3,
            "restart_delay_seconds": 60
          },
          "blink": {
            "login": {
              "username": "$${BLINK_USERNAME}",
              "password": "$${BLINK_PASSWORD}"
            },
            "history_days": 1,
            "poll_interval": 60
          },
          "rtsp_server": {
            "port": 8554
          }
        }
        EOF
        python3 -m blinkbridge.main
    volumes:
      - ./blink-session:/root/.blinkpy

  cam-recorder:
    build: .
    container_name: cam_recorder
    restart: always
    network_mode: "host"
    depends_on:
      - blink-bridge
    env_file:
      - .env
    tmpfs:
      - /tmp/cam-segments:size=256m
    volumes:
      - /mnt/data/camera-stream:/recordings
    stop_grace_period: 60s
