services:
  blink-bridge:
    build: https://github.com/roger-/blinkbridge.git
    container_name: blink_bridge
    restart: always
    network_mode: "host"
    environment:
      - BLINK_USERNAME=${BLINK_USERNAME}
      - BLINK_PASSWORD=${BLINK_PASSWORD}
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "{\"username\": \"$${BLINK_USERNAME}\", \"password\": \"$${BLINK_PASSWORD}\", \"rtsp_port\": 8554}" > config.json
        python3 -m blinkbridge
    volumes:
      - ./blink-session:/root/.blinkpy

  cam-recorder:
    build: .
    container_name: cam_recorder
    restart: always
    network_mode: "host"
    depends_on:
      - blink-bridge
    env_file:
      - .env
    tmpfs:
      - /tmp/cam-segments:size=256m
    volumes:
      - /mnt/data/camera-stream:/recordings
    stop_grace_period: 60s
